### ISSUE TITLE
不支持HTTPS的接口测试

### ISSUE THREAD

**Issue by liubiqu** [Rokid/rokid-homebase-cli#2]
https://xxx.tet.com/rokid 测试的时候会报错：

\node_modules\rokid-homebase-cli\command\list.js:28
      .then(data => {
      ^

TypeError: Cannot read property 'then' of undefined

**Comment by maxbbn** [comment]
OK 收到

**Comment by legendecas** [comment]
Resolved by 7b043a24052d92e16963d782b6a4ace326d0c4ba
